name: "version-check"
on:
  push:
    branches:
      - "*"

jobs:
  check-version:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: check version consistency
        run: |
          packageVersion=$(node -p "require('./package.json').version")
          tauriConfVersion=$(node -p "require('./src-tauri/tauri.conf.json').package.version")
          cargoVersion=$(grep -oP 'version = "\K[^"]+' src-tauri/Cargo.toml | head -n 1)

          if [[ "$packageVersion" == "$tauriConfVersion" && "$packageVersion" == "$cargoVersion" ]]; then
            echo "Version numbers are consistent."
          else
            echo "Error: Version numbers are inconsistent."
            exit 1
          fi
